# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        entry: isort
        language_version: python311
        types: [ python ]
        args: [ --profile, black, --filter-files ]
        files: \.py$
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black
        entry: black
        language_version: python311
        types: [ python ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language_version: python311
        types: [ python ]
        exclude: ^(tests/|test)
        additional_dependencies:
          - flake8-bandit==4.1.1
          - flake8-black==0.3.6
          - flake8-bugbear==23.7.10
          - flake8-cognitive-complexity==0.1.0
          - flake8-commas==2.1.0
          - flake8-comprehensions==3.14.0
          - flake8-eradicate==1.5.0
          - flake8-expression-complexity==0.0.11
          - flake8-multiline-containers==0.0.19
          - flake8-print==5.0.0
          - flake8-quotes==3.3.2
          - flake8-return==1.2.0
          - flake8-simplify==0.20.0
          - flake8-tidy-imports==4.10.0
          - flake8-use-fstring==1.4
          - pep8-naming==0.13.3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language_version: python311
        types: [ python ]
        exclude: ^(tests/|test)
        additional_dependencies:
          - types-requests==2.31.0.2
