# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort
        entry: isort
        types: [python]
        args: [--profile, black, --filter-files]
        files: \.py$
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        name: black
        entry: black
        types: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        types: [python]
        exclude: (^tests/|^test/|^run\.py$|^get_token\.py$|^fix_csv\.py$)
        additional_dependencies:
          - flake8-bandit==4.1.1
          - flake8-black==0.4.0
          - flake8-bugbear==25.11.29
          - flake8-cognitive-complexity==0.1.0
          - flake8-commas==4.0.0
          - flake8-comprehensions==3.17.0
          - flake8-eradicate==1.5.0
          - flake8-expression-complexity==0.0.11
          - flake8-multiline-containers==0.0.19
          - flake8-print==5.0.0
          - flake8-quotes==3.4.0
          - flake8-return==1.2.0
          - flake8-simplify==0.30.0
          - flake8-tidy-imports==4.12.0
          - flake8-use-fstring==1.4
          - pep8-naming==0.15.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        types: [python]
        exclude: ^(tests/|test)
        additional_dependencies:
          - types-requests==2.33.0.20260327
